export enum UserValidationErrors {
  PASSWORD_REQUIRED_ERR = 'PASSWORD_REQUIRED_ERR',
  UNIQUE_EMAIL_ERR = 'UNIQUE_EMAIL_ERR',
  INVALID_EMAIL_ERR = 'INVALID_EMAIL_ERR',
  EMAIL_REQUIRED_ERR = 'EMAIL_REQUIRED_ERR',
}
