export enum UserValidationErrors {
  USER_NOT_FOUND_ERR = 'USER_NOT_FOUND_ERR',
  PASSWORD_REQUIRED_ERR = 'PASSWORD_REQUIRED_ERR',
  UNIQUE_EMAIL_ERR = 'UNIQUE_EMAIL_ERR',
  INVALID_EMAIL_ERR = 'INVALID_EMAIL_ERR',
  EMAIL_REQUIRED_ERR = 'EMAIL_REQUIRED_ERR',
}

export enum AuthErrors {
  INCORRECT_EMAIL_ERR = 'INCORRECT_EMAIL_ERR',
  INCORRECT_PASSWORD_ERR = 'INCORRECT_PASSWORD_ERR',
  UNAUTHORIZED_ERR = 'UNAUTHORIZED_ERR',
}
